### PR TITLE
Enabled wifi support for some arduino boards #9

### PR DESCRIPTION
**Pull request by cansik**
I enabled wifi support for some arduino boards (Arduino UNO WiFi Rev.2, MKR WiFi 1010 ...) as described in #9 .

Not totally sure if they also could handle bundles, so I let it deactivated.

### CODE REVIEW

**Comment by cansik** [comment]
Maybe it makes sense to get a list from somewhere, which contains all wifi capable arduino devices, instead of adding all one-by-one.

**Comment by hideakitai** [comment]
Cool! I have checked PR and works fine for other WiFi boards. It was a critical problem but I left behind... Thanks!

**Comment by hideakitai** [comment]
@cansik Thanks again for this PR!

> Maybe it makes sense to get a list from somewhere, which contains all wifi capable arduino devices, instead of adding all on

What do you mean about this? Is it a board list described in README?

**Comment by cansik** [comment]
The library controls most of the features like bundles & SL with architecture variables (AVR, MegaAVR, SAMD). However, WiFi support is sometimes not directly related to the architecture, but to the board itself.

That's why I did not add `ARDUINO_ARCH_MEGAAVR ` to enable WiFi for the Arduino Uno Rev 2, but the actual board identifier `ARDUINO_AVR_UNO_WIFI_REV2`. As you see in the PR, there are more board identifier I just tested to compile to. But I guess there are a lot more around which I did not at yet.

So maybe there is an official list by Arduino, which explains which board has WiFi support, and which library to use (wifi101 / wifinina / ...).

But for now, this does not affect this PR :) it's more something to think about in the future.
I hope this made my comment a bit more clear.

**Comment by hideakitai** [comment]
Absolutely! I got understood what you wanna say.

FIrst, I'm changing if library use "official STLs" or "STL like container (I made)" based on architectures (`ARDUINOOSC_DISABLE_STL`). And it almost match if it can use bundles (in other words, the mcu has enough memory). So roughly defined as you said...

On the other hand, `ARDUINOOSC_ENABLE_WIFI` and `ARDUINOOSC_ENABLE_ETHER` are defined based on the board itself like you added. So maybe I left the structure as is. But absolutely we need the list of boards which has feature list (WiFi, BLE, etc.) like [this](https://en.wikipedia.org/wiki/List_of_Arduino_boards_and_compatible_systems).

Anyway, I will do compiling test, and PR will be merged soon!

**Comment by hideakitai** [comment]
Checked compiling on Arduino IDE 1.8.13. Thanks again!

**Comment by hideakitai** [comment]
close #9 .

**Pull request merged**
